// Generated by Copilot Jason v2.1 Setup - Stable Configuration
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Test Environment - Node.js für Stabilität
    environment: 'node',
    
    // Test-Dateien
    include: ['tests/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts}'],
    exclude: ['node_modules', 'dist', '.git', 'tests/securityStatic.v21.test.js'],
    
    // Stabile Reporter-Konfiguration
    reporter: ['default', 'json'],
    outputFile: './test-results.json',
    
    // Coverage mit v8 (stabil)
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage',
      include: ['scripts/**/*.js'],
      exclude: [
        'scripts/**/*.min.js',
        'scripts/**/*.test.js',
        'tests/**', 
        'node_modules/**'
      ],
      all: true,
      clean: true
    },
    
    // Timeouts
    testTimeout: 10000,
    hookTimeout: 10000,
    
    // Globals
    globals: true,
    
    // Setup
    setupFiles: [],
    
    // Watch-Optionen
    watchExclude: [
      'node_modules/**', 
      'dist/**', 
      'coverage/**', 
      'test-results.*'
    ],
    
    // Stabile Parallelisierung
    pool: 'threads',
    poolOptions: {
      threads: {
        singleThread: true // Für deterministische Tests
      }
    },
    
    // Environment Variables
    env: {
      NODE_ENV: 'test'
    }
  }
});